export const Users = [
    {
        id:1,
        profilePicture: "Person/albertdera.jpg",
        username: "Albert Dera",
    },
    {
        id:2,
        profilePicture: "Person/ayoogunseinde.jpg",
        username: "Ayoogun Seinde",
    },
    {
        id:3,
        profilePicture: "Person/brookecagle.jpg",
        username: "Brooke Cagle",
    },
    {
        id:4,
        profilePicture: "Person/christophercampbell.jpg",
        username: "Christopher Campbell",
    },
    {
        id:5,
        profilePicture: "Person/edwardcisneros.jpg",
        username: "Edward Cisneros",
    },
    {
        id:6,
        profilePicture: "Person/harpsjoseph.jpg",
        username: "Harps Joseph",
    },
    {
        id:7,
        profilePicture: "Person/juricakoletic.jpg",
        username: "Jurica Koletic",
    },
    {
        id:8,
        profilePicture: "Person/matheusferrero.jpg",
        username: "Matheus Ferrero",
    },
    {
        id:9,
        profilePicture: "Person/michaeldam.jpg",
        username: "Michael Dam",
    },
    {
        id:10,
        profilePicture: "Person/rowanchestnut.jpg",
        username: "Rowan Chestnut",
    },
];

export const Posts = [
    {
        id:1,
        photo: "Posts/fourteen.jpg",
        desc: "Natural Beauty!",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comments: 9,
        loved: 15,
    },
    {
        id:2,
        photo: "Posts/thirteen.jpg",
        date: "15 mins ago",
        userId: 2,
        like: 20,
        comments: 4,
        loved: 10,
    },
    {
        id:3,
        photo: "Posts/twelve.jpg",
        desc: "Beautiful World!",
        date: "51 mins ago",
        userId: 3,
        like: 17,
        comments: 7,
        loved: 6,
    },
    {
        id:4,
        photo: "Posts/fifteen.avif",
        desc: "Foody!",
        date: "2 hrs ago",
        userId: 4,
        like: 23,
        comments: 13,
        loved: 15,
    },
    {
        id:5,
        photo: "Posts/one.avif",
        desc: "Love for all, hatred for none!",
        date: "5 hrs ago",
        userId: 5,
        like: 12,
        comments: 3,
        loved: 25,
    },
    {
        id:6,
        photo: "Posts/six.avif",
        date: "8 hrs ago",
        userId: 6,
        like: 9,
        comments: 1,
        loved: 5,
    },
    {
        id:7,
        photo: "Posts/seven.avif",
        desc: "Am i looking handsome?",
        date: "13 hrs ago",
        userId: 7,
        like: 111,
        comments: 25,
        loved: 7,
    },
    {
        id:8,
        photo: "Posts/eight.avif",
        desc: "Hollywood!",
        date: "1 day ago",
        userId: 8,
        like: 7,
        comments: 1,
        loved: 15,
    },
    {
        id:9,
        photo: "Posts/nine.avif",
        desc: "Am i in love or not?",
        date: "3 days ago",
        userId: 9,
        like: 38,
        comments: 6,
        loved: 11,
    },
    {
        id:10,
        photo: "Posts/ten.avif",
        desc: "Yummy nn!",
        date: "5 days ago",
        userId: 10,
        like: 26,
        comments: 4,
        loved: 15,
    },
];